version: '3.7'

x-env-variables: &common-variables
  DB_HOST : 192.168.1.26
  DB_DATABASE : bp
  DB_USERNAME : victor
  DB_PASSWORD : root
  APP_KEY : ${APP_KEY}
  JWT_SECRET : ${JWT_SECRET}
  REDIS_PASSWORD : null
  APP_ENV: production
  GOOGLE_RECAPTCHA_SITE_KEY : ${GOOGLE_RECAPTCHA_SITE_KEY}
  GOOGLE_RECAPTCHA_SECRET_KEY: ${GOOGLE_RECAPTCHA_SECRET_KEY}
  SENTRY_LARAVEL_DSN: ${SENTRY_LARAVEL_DSN}
  SENTRY_TRACES_SAMPLE_RATE : ${SENTRY_TRACES_SAMPLE_RATE}


services:
  nginx:
    build: .
    restart: always
    volumes:
      - ./docker/nginx/api.black-pinthere.conf:/etc/nginx/conf.d/default.conf
      - code_vol:/usr/share/nginx/html
    environment:
      <<: *common-variables
      REDIS_HOST : redis
      REDIS_PASSWORD : null
      REDIS_PORT : 6380
    ports:
      - 8050:80
    depends_on:
      - php   
    networks:
      - bde_net


  php:
    build: ./docker/php
    restart: always
    expose:
      - "9000"
    working_dir: /usr/share/nginx/html
    links:
      - redis
    environment:
      <<: *common-variables
    volumes:
      - code_vol:/usr/share/nginx/html
    networks:
      - bde_net


  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_vol:/data
    command: redis-server --appendonly yes
    networks:
      - bde_net

volumes:
  redis_vol: {}
  code_vol : {}

networks:
  bde_net: {}
